

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

server.port=
spring.application.name=

# eureka server url
eureka.client.service-url.defaultZone=

# client registration with eureka server
eureka.client.register-with-eureka=

# fetch client details from eureka server at starting time
# cache registry details locally
eureka.client.fetch-registry=

# interval duration in which client sends heart beat to eureka server
eureka.instance.lease-renewal-interval-in-seconds=

# duration after which eureka server removes instances
eureka.instance.lease-expiration-duration-in-seconds=

# fetch registry details: refresh cache
eureka.client.registry-fetch-interval-seconds=

