spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# eureka server to remove instances for missed heart beats
eureka.server.enable-self-preservation=false

# eureka server removes stopped instances
eureka.server.eviction-interval-timer-in-ms=6000
